---
title: "eda"
author: "Anand Rajan"
date: "10/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## R Markdown
d that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this:

```{r cars}
weather_df =  
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, everything())
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
weather_df %>%
  group_by(name, month)

weather_df %>% 
  group_by(name,month) %>% 
  summarize(n_obs=n())

weather_df %>% 
  pull(name) %>% 
  table()
```

it's nice that summarize produces a data frame

'table ' doesnt, its a bad function

```{r}

```

